### ISSUE TITLE
Your README is not clear

### ISSUE THREAD

**Issue by MindfulMe** [dariomac/poc-cra-ssr#3]
Put proper launch commands.

Do:
```
npm i
npm start
npm run start-server
```

**Comment by dariomac** [comment]
You are right Rostilav, I thought I wrote them in the  article https://www.vairix.com/tech-blog/server-side-rendering-ssr-of-create-react-app-cra-app-in-2020 but that wasn't the case.

Thank you very much for noticing and letting me know.

**Comment by dariomac** [comment]
Done here https://github.com/dariomac/poc-cra-ssr/commit/c55f9ad96975a5f29ed058eaac82fef3d752bb39 @MindfulMe

**Comment by MindfulMe** [comment]
@dariomac I put my react app in your example and I get error minor error with babel, I searched the whole google but still not able to resolve that simple thing with babel. I have a relatively small react app done with create-react-app.



See StackOverflow https://stackoverflow.com/questions/62475958/babel-transform-error-property-value-expected-type-of-string-but-got-object :)

**Comment by dariomac** [comment]
@MindfulMe, I'm not having any trouble with Node v12.13.0 using your bootstrap.js code.

I even tried with an empty & clean CRA project and it works without any change. I've updated the code of the Github repo to the latest version of every dependency.

Please, test it and let me know if that solved the issue.
